#!/usr/bin/env bash
set -euo pipefail

if [[ $# -ne 2 ]]; then
  echo "Usage: $0 <esp32-device> <lidar-device>" >&2
  echo "Example: $0 /dev/ttyUSB0 /dev/ttyUSB1" >&2
  exit 2
fi

property() {
  local device="$1"
  local key="$2"
  udevadm info --query=property --name="${device}" |
    awk -F= -v key="${key}" '$1 == key { print $2; exit }'
}

rule_for() {
  local device="$1"
  local symlink="$2"
  local vendor product serial id_path

  vendor="$(property "${device}" ID_VENDOR_ID)"
  product="$(property "${device}" ID_MODEL_ID)"
  serial="$(property "${device}" ID_SERIAL_SHORT)"
  id_path="$(property "${device}" ID_PATH)"

  if [[ -z "${vendor}" || -z "${product}" ]]; then
    echo "ERROR: Could not identify USB IDs for ${device}." >&2
    exit 1
  fi

  printf 'SUBSYSTEM=="tty", ATTRS{idVendor}=="%s", ATTRS{idProduct}=="%s"' \
    "${vendor}" "${product}"
  # Cheap CP2102 adapters often share serial "0001". Bind to the USB port
  # path so ESP32 and LiDAR do not collide.
  if [[ -n "${id_path}" ]]; then
    printf ', ENV{ID_PATH}=="%s"' "${id_path}"
  elif [[ -n "${serial}" ]]; then
    printf ', ENV{ID_SERIAL_SHORT}=="%s"' "${serial}"
  fi
  printf ', SYMLINK+="%s", GROUP="dialout", MODE="0660"\n' "${symlink}"
}

esp_rule="$(rule_for "$1" kiwi_esp32)"
lidar_rule="$(rule_for "$2" kiwi_lidar)"

if [[ "${esp_rule}" == "${lidar_rule}" ]]; then
  echo "ERROR: ${1} and ${2} produce the same udev match." >&2
  echo "Identify each device, then keep them on different USB ports." >&2
  exit 1
fi

tmp_file="$(mktemp)"
trap 'rm -f "${tmp_file}"' EXIT

{
  echo '# Generated by 3-Axis-Holonomic-Drive-Robot/scripts/install_udev_rules.sh'
  echo "${esp_rule}"
  echo "${lidar_rule}"
} >"${tmp_file}"

sudo install -m 0644 "${tmp_file}" /etc/udev/rules.d/99-kiwi-robot.rules
sudo udevadm control --reload-rules
sudo udevadm trigger

echo "Installed /etc/udev/rules.d/99-kiwi-robot.rules"
echo "Keep each device in the same USB port. Reconnect both, then verify:"
echo "  ls -l /dev/kiwi_esp32 /dev/kiwi_lidar"
echo "Rules:"
echo "  ${esp_rule}"
echo "  ${lidar_rule}"
