#!/usr/bin/env bash
set -euo pipefail

if [[ $# -ne 2 ]]; then
  echo "Usage: $0 <esp32-device> <lidar-device>" >&2
  echo "Example: $0 /dev/ttyUSB0 /dev/ttyUSB1" >&2
  exit 2
fi

property() {
  local device="$1"
  local key="$2"
  udevadm info --query=property --name="${device}" |
    awk -F= -v key="${key}" '$1 == key { print $2; exit }'
}

rule_for() {
  local device="$1"
  local symlink="$2"
  local vendor product serial

  vendor="$(property "${device}" ID_VENDOR_ID)"
  product="$(property "${device}" ID_MODEL_ID)"
  serial="$(property "${device}" ID_SERIAL_SHORT)"

  if [[ -z "${vendor}" || -z "${product}" ]]; then
    echo "ERROR: Could not identify USB IDs for ${device}." >&2
    exit 1
  fi

  printf 'SUBSYSTEM=="tty", ATTRS{idVendor}=="%s", ATTRS{idProduct}=="%s"' \
    "${vendor}" "${product}"
  if [[ -n "${serial}" ]]; then
    printf ', ENV{ID_SERIAL_SHORT}=="%s"' "${serial}"
  fi
  printf ', SYMLINK+="%s", GROUP="dialout", MODE="0660"\n' "${symlink}"
}

tmp_file="$(mktemp)"
trap 'rm -f "${tmp_file}"' EXIT

{
  echo '# Generated by 3-Axis-Holonomic-Drive-Robot/scripts/install_udev_rules.sh'
  rule_for "$1" kiwi_esp32
  rule_for "$2" kiwi_lidar
} >"${tmp_file}"

sudo install -m 0644 "${tmp_file}" /etc/udev/rules.d/99-kiwi-robot.rules
sudo udevadm control --reload-rules
sudo udevadm trigger

echo "Installed /etc/udev/rules.d/99-kiwi-robot.rules"
echo "Reconnect both USB devices, then verify /dev/kiwi_esp32 and /dev/kiwi_lidar."
